---
title: "README runthrough"
format: html
editor: visual
---

## Survey Research Methodology Assignment

Frederick Peña, Alexandra Salo and Sofia Villamil, 2024

In this assignment we seek to explaining Cross-Country Differences in support for transgender individuals obtaining official documents (cq19 in the questionnare) and then to continue and create a predictive model to predict the support levels of other countries.

1.  Loading data and cleaning the data

First we loaded the data and proceeded to clean the data.

2.  Adding extra country level variables

In order to fully examine the support of transgender access to documents, and especially to be able to predict the support in other countries, it is important that we examine things on a macro-level as well. For this work we decided to include these country level variables.

-   Legal variables, we included a variable that showed the country level legal rights of transgender individuals. We were able to find a variable that shows this, which is an index created by the Harvard Dataverse, TRIP (ref) <https://doi.org/10.7910/DVN/FXXLTS,>

-   Economic variables, for this analysis we considered that economic variables are usually quite important in general, we wanted to see if they may be influential for this analysis as well. For this purpose we chose two benchmark economic variables, GDP and unemployment, these can give us valuable information about the health of an economy and a society at large. (ref- Citation: World Bank. (n.d.). DataBank: World Development Indicators \[Economy & Growth\]. Retrieved March 13, 2024, from <https://databank.worldbank.org/source/world-development-indicators>)

Descriptive analysis

Since the dataset to start with was extremely big, we first tried reducing variables according to significance and correlation. We quickly realized that this wasn't enough and we were still left with hundred of variables, so we came up with a new approach to selecting the main variables we would be using. Our approach was to skim existing literature about variables that may be of interest when considering our target variable, which boils down ultimately to the support of legal integration of transgender individuals into society. Once existing literature was found in relations to one or more of the variables, we tried to find this variable in our dataset, or at least a similar variable and conducted tests to see if they were significant in relations to the target variable. We conducted this approach one variable at a time until we had gone through FIX **ABOUT 10 VARIABLES.**

**Gender**

According to the literature we had found, we assumed that men would be less supportive in the target variable. (FIX SOMETHING MORE ABOUT THE LIT) We found that this was true in our data with almost half of men against the question of the target variable.

**Binary conception of gender**

According to the literature we had found, if you had a binary conception of gender, so if you only thought there were 2 genders to start with, you could be less supportive of the legal integration of transgender individuals. (FIX LIT)

In order to test this correlation we conducted a Spearman rank test on the dependent variable and the variable qc_20, which asks if there should be a third gender option. We use this method because the country-level proportions are not normally distributed. Based on the outputs of the test, we conclude the null hypothesis X? and conclude that there is a significant relationship between the target variable and the binary conception of gender, supporting prior literature. We even note that 88.29% of those against a third gender option also negate the option for transgender persons to change their gender in civil documents. We also visualize this in two plots, and see many of the same countries in the top and bottom of both graphs.

**Political ideology**

Literature dictates that political ideology influences the support for FIX XXXX

In order to test this relationship we used the same Spearman rank test on the dependent variable and the variable d_10. We find interesting results here, as 25% of the respondents chose the exact middle ground on the political ideology scale, so 5 (from 1 to 10). We see that the inherent idea is upheld that a greater share of more left-leaning people are in favor of the dependent variable, however, difference to very right-leaning people is not that great (60-30 left vs. 43-45 right). We note here that the self-reporting self-right scale might not be so accurate and people may be more right or left leaning than they self-report.

-   a lot of information is hidden in the non-response and don't know groups of political ideology as they have greater don't know rates for qc19 ?

    Our main takeaway from this analysis is that political ideology has a significant association (but maybe not as strong as suspected). We visualize these differences in the end. We also want to note that here we binned Don't Know answers and Refusals to answer in the same category, which could skew the way we think about those that answered about their political ideology here.

**Religion**

In literature we found, they note that FIX XXXXX

So thus we look to religion which is included in the survey. First we cluster some of the religions to reduce the amount of categories in religion. Even clustering we noted that there were very small amounts of respondents for European minority religious groups, for example Jewish, Muslim or other religious people, so making conclusions about these groups are not very reliable.

However we do note some interesting conclusions supporting the literature FIX??, on the individual level not believing in God has a positive relationship with support in the dependent variable. We note that generally Catholics are in favor but less strongly as the non-believers or Protestants. The outlier in this analysis is clearly the Orthodox Christians as they don't report support in the target variable. Roughly one could thus say that countries with a higher share of Orthodox Christians may be against the legal recognition of transgender individuals.

FIX LIT?

**Contact**

Literature FIX XXX shows that having a transgender contact or relationship in your life significantly affects your support for transgender rights.

In our analysis we find that this association is statistically significant. There is a clear tendency on the individual level that among those that have not had contact with a transgender person the approval is relatively lower as for those who have had the margin is very clear (76% vs 18%). We note that the survey respondents show that a majority of people did not have contact with a transgender person at all. Not having had contact to a transgender individual is not associated with being against or responding No in the dependent variable, just lower approval in the target variable. We visualize this relationship as well.

**Age**

Literature XXX

In our analysis we use an ANOVA test to test for significant differences between the different answers in the dependent variable 'Yes', 'No', 'Don't know' and 'Refuse' by age. The analysis confirms that we can reject our null hypothesis that there are no differences in means between groups, thus we know that there are statistically significant differences between at least 2 groups. We use boxplots to visualize these differences, and we show that the strongest difference is between those saying 'yes' and those stating 'don't know'. This conveys valuable information from particularly older people, it could be said that thus in older demographics it is more common to have confused or unclear sentiments about the issue. We also see a slight difference between 'Yes' and 'No' in age, and see that older generations are slightly more inclined to say No in the target variable.

**Awareness**
